[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[features]
default = ["tracing-log", "metrics"]
# Enables support for exporting OpenTelemetry metrics
metrics = ["opentelemetry/metrics","opentelemetry_sdk/metrics", "smallvec"]
# Enables experimental support for OpenTelemetry gauge metrics
metrics_gauge_unstable = ["opentelemetry/otel_unstable"]

[dependencies]
opentelemetry = { version = "0.27.0", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "0.27.0", default-features = false, features = ["trace"] }
tracing = { version = "0.1.35", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["registry", "std", "chrono"] }
tracing-log = { version = "0.2.0", default-features = false, optional = true }

# Work around incorrect minimal version in opentelemetry, https://github.com/open-telemetry/opentelemetry-rust/pull/2406
smallvec = { version = "1.0", optional = true }

opentelemetry-stdout = { version = "0.27.0", features = ["trace", "metrics"] }
opentelemetry-otlp = { version = "0.27.0", features = ["metrics"] }
opentelemetry-semantic-conventions = { version = "0.27.0", features = ["semconv_experimental"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing-error = "0.2.0"
tracing-opentelemetry = { version = "0.28.0", features = ["metrics", "tracing-log", "async-trait"] }
